# Tensorflow Basic

In [2]:
# Importing Tensorflow

import tensorflow as tf

In [3]:
# Checking variable
tf.__version__

'2.0.0'

### Storage Types

# Constants

>tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const'
)

In [4]:
# Constant of type string
print(tf.constant("Hello World"))

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [5]:
# Constant 1-D Tensor populated with value list.
print(tf.constant([1, 2, 3, 4, 5, 6]))

# Constant 1-D Tensor populated with value list.
print(tf.constant([1, 2, 3, 4, 5, 6], shape=(2,3)))

# Constant 2-D tensor populated with scalar value -1.
print(tf.constant(-1.0, shape=[2, 3]))

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-1. -1. -1.]
 [-1. -1. -1.]], shape=(2, 3), dtype=float32)


In [52]:
# Mathematical operation
con1 = tf.constant(21)
con2 = tf.constant(10)

print((con1+con2))
print((con1*con2).numpy())
print((con1/con2).numpy())
print((con1%con2).numpy())

tf.Tensor(31, shape=(), dtype=int32)
210
2.1
1


In [36]:
tf.fill((5,5),10)

<tf.Tensor: id=269, shape=(5, 5), dtype=int32, numpy=
array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])>

In [37]:
tf.zeros((5,5))

<tf.Tensor: id=272, shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [41]:
tf.ones((5,5))

<tf.Tensor: id=284, shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [40]:
tf.ones((5,5)).shape

TensorShape([5, 5])

### Variables

In [44]:
my_tensor = tf.random_uniform_initializer((5,5),0,2)

In [47]:
my_tensor

In [50]:
import tensorflow as tf
A = tf.Variable([[1,2,3], [4,5,6], [7,8,9]], dtype=tf.float32)
with tf.compat.v1.Session() as sess:
  sess.run(tf.compat.v1.global_variables_initializer())
  print(sess.run(A[:2, :2]))  # => [[1,2], [4,5]]

  op = A[:2,:2].assign(22. * tf.ones((2, 2)))
  print(sess.run(op))  # => [[22, 22, 3], [22, 22, 6], [7,8,9]]

RuntimeError: Attempting to capture an EagerTensor without building a function.